### ISSUE TITLE
@paginate decorator doesn't work with QuerySet

### ISSUE THREAD

**Issue by dolgidmi** [eadwinCode/django-ninja-extra#68]
Hi, 

Basically the same code as the pagination example in docs:
```
@api_controller('municipalities')
class MunicipalitiesController(ControllerBase):
    @route.get('', response=NinjaPaginationResponseSchema[MunicipalitySchema])
    @paginate
    def get_list(self):
        return Municipality.objects.all()
```
ends up with exception
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ninja_extra/operation.py", line 189, in run
    _processed_results = self._result_to_response(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ninja/operation.py", line 202, in _result_to_response
    result = response_model.from_orm(resp_object).dict(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ninja/schema.py", line 164, in from_orm
    return super().from_orm(obj)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 579, in from_orm
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for NinjaResponseSchema
response -> items
  value is not a valid list (type=type_error.list)
```

Works fine with a list though, but I don't really want to query all 6k rows :)
```
@route.get('', response=NinjaPaginationResponseSchema[MunicipalitySchema])
    @paginate
    def get_list(self):
        return [item for item in Municipality.objects.all()]
```

```
django-ninja>=0.22,<1.0
django-ninja-extra>=0.19,<1.0
```

**Comment by dolgidmi** [comment]
`PageNumberPaginationExtra` works fine due to type casting https://github.com/eadwinCode/django-ninja-extra/blob/0b2a6a8b0cf6145594b6d8cd148d1a7a8b7bec49/ninja_extra/pagination.py#LL107C23-L107C23

**Comment by eadwinCode** [comment]
@dolgidmi If you using `Ninja` pagination class with `ninja_extra` paginate decorator, you need to use `NinjaPaginationResponseSchema` on the response model. So yeah,
```python
from ninja_extra.schemas import NinjaPaginationResponseSchema

@route.get('', response=NinjaPaginationResponseSchema[MunicipalitySchema])
@paginate
def get_list(self):
    return  Municipality.objects.all() # works with queryset
```
Works

But you can use `ninja` paginate decorator if you want the first case to work fine. 

`ninja_extra` paginate works for sync and async function which is not the same for `ninja` paginate at the moment. 

So let me know if this works for you

**Comment by eadwinCode** [comment]
@dolgidmi This has been fixed

**Comment by dolgidmi** [comment]
@eadwinCode thx! Can’t wait for PyPI release :)

**Comment by dolgidmi** [comment]
@eadwinCode still getting the same error for empty QuerySet, but I guess it should be easy to fix.
```
        def validate_items(cls, value: Any) -> Any:
            if value and not isinstance(value, list):
                return list(value)
            return value
```
Basically because `bool(QuerySet([])) =  False` (same as en empty list), it won't be converted to the normal list.

**Comment by eadwinCode** [comment]
@dolgidmi Here is a fix https://github.com/eadwinCode/django-ninja-extra/pull/73

**Comment by dolgidmi** [comment]
@eadwinCode thx! PyPI release would be nice :)
